version: '3'

services:
  app:
    container_name: app
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY_NAME}:${IMAGE_TAG}
    ports:
      - "8080:8080"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 800M
